language: generic
services:
  - docker

env:
  matrix:
    - ROS_DISTRO="kinetic" ROS_REPO=ros NOT_TEST_INSTALL=true CATKIN_LINT=true
    - ROS_DISTRO="dashing" ROS_REPO=ros NOT_TEST_INSTALL=true

install:
  - git clone --depth=1 -b master https://github.com/ros-industrial/industrial_ci.git .ci_config

script:
  - .ci_config/travis.sh
